import { ReactNode } from 'react';
import { ChainProvider } from './commons/ChainContext';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChainProvider>
          {children}
        </ChainProvider>
      </body>
    </html>
  )
}
